---
- name: homebox playbook
  hosts: localhost
  connection: local

  pre_tasks:
    - name: update system
      become: true
      become_user: root
      ansible.builtin.dnf5:
        name: "*"
        state: latest
        update_cache: true

    - name: install system dependencies
      become: true
      become_user: root
      ansible.builtin.dnf5:
        name:
          - python-dnf
          - nodejs
          - nodejs-npm
          - stow
          - cargo
        state: present

    # this is required to allow globally installing node packages without 'become'
    - name: npm install global packages on user home
      ansible.builtin.lineinfile:
        path: ~/.npmrc
        regexp: '^prefix='
        line: prefix=~/.local/

  tasks:
    - name: install cli tools
      become: true
      become_user: root
      ansible.builtin.dnf5:
        name:
          - fzf
          - ripgrep
          - fd-find
          - eza
          - bat
          - fish
          - tmux
          - zoxide
          - pinentry
          - jq
          - htop
        state: present
      tags:
        - cli
        - tools

    - name: fix missing xterm-kitty terminfo
      become: true
      become_user: root
      ansible.builtin.dnf5:
        name: kitty-terminfo
        state: present
      tags:
        - kitty

    - name: neovim
      ansible.builtin.import_tasks: neovim/main.yaml

    - name: install process-compose
      ansible.builtin.shell: "{{ playbook_dir }}/../scripts/install-process-compose.sh"
      args:
        creates: ~/.local/bin/process-compose
      tags:
        - process-compose

    # foot has some conflicts with neovim, skipping for now
    # this has to after neovim as both install utf8proc, but neovim needs the git version
    # - name: install foot
    #   become: true
    #   become_user: root
    #   ansible.builtin.dnf5:
    #     name:
    #       - foot
    #       - foot-terminfo
    #     state: present
    #   tags:
    #     - foot
