---
- name: setup homebox
  hosts: localhost
  connection: local

  pre_tasks:
    - name: update system
      become: true
      become_user: root
      ansible.builtin.dnf5:
        name: "*"
        state: latest
        update_cache: true
    - name: install system dependencies
      become: true
      become_user: root
      ansible.builtin.dnf5:
        name:
          - python-dnf
          - nodejs
          - nodejs-npm
          - stow
        state: present
    - name: npm install global packages on user home
      ansible.builtin.lineinfile:
        path: ~/.npmrc
        regexp: '^prefix='
        line: prefix=~/.local/

  tasks:
    - name: install cli tools
      become: true
      become_user: root
      ansible.builtin.dnf5:
        name:
          - fzf
          - ripgrep
          - fd-find
          - eza
          - bat
          - fish
        state: present
      tags:
        - cli

    - name: enable lazygit copr
      become: true
      become_user: root
      community.general.copr:
        state: enabled
        name: atim/lazygit
      tags:
        - lazygit

    - name: install lazygit
      become: true
      become_user: root
      ansible.builtin.dnf5:
        name: "lazygit"
        state: present
      tags:
        - neovim

    - name: enable neovim nightly copr
      become: true
      become_user: root
      community.general.copr:
        state: enabled
        name: agriffis/neovim-nightly
      tags:
        - neovim

    - name: install neovim
      become: true
      become_user: root
      ansible.builtin.dnf5:
        name: "neovim"
        state: present
      tags:
        - neovim

    - name: set lua-language-server version
      when: (lua_ls_version is not defined) or (lua_ls_version == 'latest')
      run_once: true
      block:
        - name: get download url
          ansible.builtin.uri:
            url: "https://api.github.com/repos/LuaLS/lua-language-server/releases/latest"
            body_format: json
          register: _lua_ls_github_release
          until: _lua_ls_github_release.status == 200
          retries: 5
        - name: set lua_ls_version
          ansible.builtin.set_fact:
            lua_ls_version: "{{ _lua_ls_github_release.json.tag_name | regex_replace('^v?(.*)$', '\\1') }}"
      tags:
        - neovim

    - name: install lua-language-server
      block:
        - name: make directory
          ansible.builtin.file:
            path: ~/.local/lua-language-server
            state: directory
            mode: '0755'
        - name: download release
          ansible.builtin.unarchive:
            src: "https://github.com/LuaLS/lua-language-server/releases/download/{{ lua_ls_version }}/lua-language-server-{{ lua_ls_version }}-linux-x64.tar.gz"
            dest: ~/.local/lua-language-server
            creates: ~/.local/lua-language-server/bin/lua-language-server
            remote_src: true
        - name: link to $PATH
          ansible.builtin.file:
            src: ~/.local/lua-language-server/bin/lua-language-server
            dest: ~/.local/bin/lua-language-server
            state: link
      tags:
        - neovim

    - name: set stylua version
      when: (stylua_version is not defined) or (stylua_version == 'latest')
      run_once: true
      block:
        - name: get download url
          ansible.builtin.uri:
            url: "https://api.github.com/repos/JohnnyMorganz/StyLua/releases/latest"
            body_format: json
          register: _stylua_github_release
          until: _stylua_github_release.status == 200
          retries: 5
        - name: set stylua_version
          ansible.builtin.set_fact:
            stylua_version: "{{ _stylua_github_release.json.tag_name }}"
      tags:
        - neovim

    - name: install stylua
      block:
        - name: make directory
          ansible.builtin.file:
            path: ~/.local/stylua
            state: directory
            mode: '0755'
        - name: download release
          ansible.builtin.unarchive:
            src: "https://github.com/JohnnyMorganz/StyLua/releases/download/{{ stylua_version }}/stylua-linux-x86_64.zip"
            dest: ~/.local/stylua
            remote_src: true
            creates: ~/.local/stylua/stylua
        - name: link to $PATH
          ansible.builtin.file:
            src: ~/.local/stylua/stylua
            dest: ~/.local/bin/stylua
            state: link
      tags:
        - neovim

    - name: install neovim tools
      become: true
      become_user: root
      ansible.builtin.dnf5:
        name:
          - shfmt
          - ShellCheck
          - fzf
          - ripgrep
          - fd-find
          - bat
          - fswatch
          - nodejs-bash-language-server
        state: present
      tags:
        - neovim

    - name: install npm dependencies for neovim
      community.general.npm:
        name: "{{ item }}"
        global: true
        state: present
      loop:
        - "@fsouza/prettierd"
        - "eslint_d"
        - "@vue/language-server"
        - "@vtsls/language-server"
        - "vscode-langservers-extracted"
      tags:
        - neovim
