---
- name: set lua-language-server version
  when: (lua_ls_version is not defined) or (lua_ls_version == 'latest')
  run_once: true
  block:
    - name: get download url
      ansible.builtin.uri:
        url: "https://api.github.com/repos/LuaLS/lua-language-server/releases/latest"
        body_format: json
      register: _lua_ls_github_release
      until: _lua_ls_github_release.status == 200
      retries: 5
    - name: set lua_ls_version
      ansible.builtin.set_fact:
        lua_ls_version: "{{ _lua_ls_github_release.json.tag_name | regex_replace('^v?(.*)$', '\\1') }}"
  tags:
    - neovim

- name: install lua-language-server
  block:
    - name: make directory
      ansible.builtin.file:
        path: ~/.local/lua-language-server
        state: directory
        mode: '0755'
    - name: download release
      ansible.builtin.unarchive:
        src: "https://github.com/LuaLS/lua-language-server/releases/download/{{ lua_ls_version }}/lua-language-server-{{ lua_ls_version }}-linux-x64.tar.gz"
        dest: ~/.local/lua-language-server
        creates: ~/.local/lua-language-server/bin/lua-language-server
        remote_src: true
    - name: link to $PATH
      ansible.builtin.file:
        src: ~/.local/lua-language-server/bin/lua-language-server
        dest: ~/.local/bin/lua-language-server
        state: link
  tags:
    - neovim

