- name: set stylua version
  when: (stylua_version is not defined) or (stylua_version == 'latest')
  run_once: true
  block:
    - name: get download url
      ansible.builtin.uri:
        url: "https://api.github.com/repos/JohnnyMorganz/StyLua/releases/latest"
        body_format: json
      register: _stylua_github_release
      until: _stylua_github_release.status == 200
      retries: 5
    - name: set stylua_version
      ansible.builtin.set_fact:
        stylua_version: "{{ _stylua_github_release.json.tag_name }}"
  tags:
    - neovim

- name: install stylua
  block:
    - name: make directory
      ansible.builtin.file:
        path: ~/.local/stylua
        state: directory
        mode: '0755'
    - name: download release
      ansible.builtin.unarchive:
        src: "https://github.com/JohnnyMorganz/StyLua/releases/download/{{ stylua_version }}/stylua-linux-x86_64.zip"
        dest: ~/.local/stylua
        remote_src: true
        creates: ~/.local/stylua/stylua
    - name: link to $PATH
      ansible.builtin.file:
        src: ~/.local/stylua/stylua
        dest: ~/.local/bin/stylua
        state: link
  tags:
    - neovim

