---
- name: blueetooth | disable idle timeout
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/bluetooth/input.conf
    regexp: '^IdleTimeout='
    line: 'IdleTimeout=0'
    insertafter: '^#IdleTimeout='

- name: blueetooth | enable fast connectable
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    path: /etc/bluetooth/main.conf
    regexp: '^FastConnectable='
    line: 'FastConnectable=0'
    insertafter: '^#FastConnectable ='
